default: &default
  adapter: postgresql
  encoding: utf8
  username: Chandan
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
